auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    s3:
      endpoint: s3.${aws_region}.amazonaws.com
      bucketnames: ${s3_bucket}
      region: ${aws_region}
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6

# chunk_store_config removed in Loki 3.x

# table_manager removed in Loki 3.x - use compactor instead
compactor:
  working_directory: /loki/compactor
  retention_enabled: false

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  # alertmanager_url: http://localhost:9093  # Commented out - no Alertmanager configured
  ring:
    kvstore:
      store: inmemory
  enable_api: true